features:
  - r_ext_pAl
  - r_ext_pMeO
  - pAl_richness

targets:
  - Pg_f
  - Tg_Tmax

additional_values:
  - sim_time
  - error

variables_ranges:
  base:
    r_ext_pAl: {bounds: [2.0e-7, 1.0e-5], scale: lin, discete_steps: 0}
    r_ext_pMeO: {bounds: [2.0e-7, 1.0e-5], scale: lin, discete_steps: 0}
    pAl_richness: {bounds: [1, 4], scale: lin, discete_steps: 0}
    Pg_f: {bounds: [0.2e+6, 60.0e+6], scale: lin}
    Tg_Tmax: {bounds: [2000, 8000], scale: lin}

  wide_target:
    Pg_f: {bounds: [0.2e+6, 150.0e+6], scale: log}
    Tg_Tmax: {bounds: [600, 7500], scale: log}

interest_region:
  Pg_f: [40.0e+6, 56.0e+6]
  Tg_Tmax: [5800, 7000]

simulator_config:
  use: true
  max_sim_time: 1200  # seconds

batch_size: 8

stop_condition:
  max_inliers: 200
  max_interest: 50
  stop_on_max_inliers: true