#!/bin/bash

# requests for pfcalcul

sacct_list () {
	start_date=$1
	end_date=$2
	states=$3

	sacct --starttime=$start_date --endtime=$end_date --state=$states --format=Start,State%10,JobID%7,JobName%40,Elapsed,Timelimit | sort -k 1 | grep -v ' batch ' | grep -v monopy 
}

sacct_count () {
	start_date=$1
	end_date=$2
	states=$3

	lines_tot=$(sacct --starttime=$start_date --endtime=$end_date --state=$states | grep -v ' batch ' | grep -v monopy | wc -l)
	jobs_tot=$(( $lines_tot - 2 ))

	echo -e "----- Sacct request -----\n"
	echo "Start date : $start_date"
	echo "End date   : $end_date"
	echo "States	   : $states"
	echo "Total lines: $lines_tot"
	echo "Total jobs : $jobs_tot"
}

# ---MAIN---

date_format="+%Y-%m-%dT%H:%M:%S"  # e.g. "2021-06-19T08:00:00"

start_date_monday=$(date -d 'last monday' $date_format)
start_date_7days=$(date -d '- 7 day' $date_format)
start_date_3days=$(date -d '- 3 day' $date_format)

end_date=$(date $date_format)

states="COMPLETED,CANCELLED,TIMEOUT,RUNNING"

request="$start_date_7days $end_date $states"

echo -e "\nlaunch: sacct_list $request\n"
sacct_list $request


echo -e "\nlaunch: sacct_count $request\n"
sacct_count $request

echo -e "\n"

