#!/bin/sh -e

export PATH=/usr/bin:${PATH}

DIR=$(cd ${0%/*}; pwd)
cd ${DIR}

help()
{
    echo
    echo "Give 'program name' as first argument"
    echo "It is possible to pass python script args or sbatch args."
    echo "Use following syntaxe:"
    echo "$1 [program_name] [prog_arg1] [parg_arg2] ... [-- [sbatch] [args]]"
    echo
    exit 0
}

if [ -z "$1" ]; then
    echo "Give 'program name' as first argument or -h for help"
    exit 1
elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    help $0
fi

prog_name=${1}
shift 1

if [ ! command -v ${prog_name} &> /dev/null ]; then
    echo "'${prog_name}' could not be found"
    exit 1
fi

prog_args=""
is_prog_args=true

while [ "$1" != "" ] && $is_prog_args; do

    if [ "$1" = "--" ]; then
        is_prog_args=false
    else
        prog_args="${prog_args} $1"
    fi
    shift

done

# shift user args to enable eventual sbatch options
# (shift n: deletes ${1, ..., n} and shifts ${k}->${k-n})

echo
echo "prog_name='${prog_name}'"
echo "prog_args  ='${prog_args}'"

# Name of job, EXEC is an exported variable, its name should be unchanged
EXEC="adasamp_jobs"

# Command to execute in sub-sbatch
EX="${prog_name} ${prog_args}"

. /pfcalcul/tools/sbatchHelpers2.sh

jobMessage=$(
######################### SBATCH launcher
#########################     #SBATCH --option        # <= this is an enabled paramater
#########################     ##SBATCH --option       # <= this is a disabled parameter
sbatch ${sbatchopt} << eof
#!/bin/bash
#SBATCH --job-name="$(basename ${prog_name})"
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=3G
#SBATCH --output=stdout.txt
#SBATCH --error=stderr.txt
#SBATCH --account=team_neo   
#SBATCH --partition=neo

# --mem-per-cpu: default maximum is 3.5GB
# example: reserving 100GBytes per task (allowing max 256G/100G=2 tasks per node)
####SBATCH --mem-per-cpu=100G

# define default job name with exported variables
####SBATCH --job-name="${EXECDIR}-${LOGNAME}"

# activate mail notfication when submitting jobs
####SBATCH --mail-type=ALL

# restrict all taks on ***the same node***
####SBATCH --nodes=1-1

. /pfcalcul/tools/sbatchHelpers2.sh

#### User customization -------------

echo

echo "default_python3=$(which python3)" 
echo "venv=${DIR}/venv/bin/activate"

. ${DIR}/venv/bin/activate

eval echo "used_python3=\$(which python3)"
eval echo "version=\$(python3 --version)"
echo "EX=${EX}"
echo "pwd=$(pwd)"

#### End of user customization ------

time $EX

eof
)

showSubmitted
